//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiselaWeb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwExpens
    {
        public string ExpenseTypeName { get; set; }
        public double Amount { get; set; }
        public string Name { get; set; }
        public int ExpenseId { get; set; }
    }
}
