//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiselaWeb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwOrderCustomer
    {
        public string Name { get; set; }
        public string Phone { get; set; }
        public Nullable<double> Bill { get; set; }
        public Nullable<double> Tendered { get; set; }
        public Nullable<int> Customer { get; set; }
        public string SaleType { get; set; }
        public int SaleId { get; set; }
        public Nullable<System.DateTime> DateSold { get; set; }
    }
}
