//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiselaWeb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwReceivingReport
    {
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string TaxStatus { get; set; }
        public string CategoryName { get; set; }
        public string BrandName { get; set; }
        public Nullable<double> OrderPrice { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
    }
}
