//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiselaWeb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwUpdateStock
    {
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public Nullable<double> Shop { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<double> SellingPrice { get; set; }
        public Nullable<int> ShopId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public int StockId { get; set; }
        public Nullable<double> Stores { get; set; }
    }
}
